### ISSUE TITLE
Migrate presubmit to Prow

### ISSUE THREAD

**Issue by sebastienvas** [istio/broker#17]
Create a broker-presubmit job in Prow and disable it from Jenkins.

**Comment by xiaolanz** [comment]
broker hasn't any integration test yet. would you please show me an example PR?

**Comment by sebastienvas** [comment]
No but it as a presubmit https://github.com/istio/broker/blob/master/Jenkinsfile#L37.

Nick documented the steps here
https://github.com/istio/test-infra/tree/master/prow#creating-a-job-on-your-repo

Here is an example
Auth presubmit, prow config: https://github.com/istio/test-infra/blob/master/prow/config.yaml#L38
Actual presubmit https://github.com/istio/auth/blob/master/prow/auth-presubmit.sh
