### ISSUE TITLE
broker e2e is creating test namespace in Prow cluster instead of e2e cluster

### ISSUE THREAD

**Issue by sebastienvas** [istio/broker#22]
Make sure your e2e points to the .kube/config that we mount in the prow jobs

**Comment by xiaolanz** [comment]
the test hasn't been check in yet. I will change it back.

**Comment by sakshigoel12** [comment]
xiaolanz@ can you update this?

**Comment by xiaolanz** [comment]
I think it should be fixed. Can you verify?
