### ISSUE TITLE
Create a etcd client library for broker storage

### ISSUE THREAD

**Issue by xiaolanz** [istio/broker#30]
The storage is accessed by mixer adapter too.

**Comment by kyessenov** [comment]
Issue moved to [istio/istio #1489](https://github.com/istio/istio/issues/1489) via [**ZenHub**](https://www.zenhub.com/)

**Comment by kyessenov** [comment]
Issue moved to [istio/istio #1490](https://github.com/istio/istio/issues/1490) via [**ZenHub**](https://www.zenhub.com/)
